import type { AppAdminProfile, PendingProfile } from "~/lib/admin/types"

// list_pending_profiles가 내려주는 순서 그대로다: onboarding_completed_at 오름차순 --
// 오래 기다린 신청이 위. 최신순이면 밀린 사람이 영영 아래에 깔린다.
export const mockPendingProfiles: PendingProfile[] = [
  {
    id: 301,
    name: "강민준",
    type: "student",
    studentNumber: "300315",
    classNo: 3,
    cohort: 30,
    gender: "male",
    track: "domestic",
    department: null,
    isReenrolled: false,
    phoneNumber: "010-2314-8890",
    birthday: "2008-03-15",
    dormRoom: 412,
    description: "잘 부탁드립니다!",
    avatarUrl: null,
    submittedAt: "2026-07-11T09:12:00.000Z",
  },
  {
    id: 302,
    name: "이서윤",
    type: "student",
    studentNumber: "300127",
    classNo: 1,
    cohort: 30,
    gender: "female",
    track: "international",
    department: null,
    isReenrolled: false,
    phoneNumber: "010-7742-1103",
    birthday: "2008-01-27",
    dormRoom: 318,
    description: null,
    avatarUrl: null,
    submittedAt: "2026-07-11T14:40:00.000Z",
  },
  {
    id: 303,
    name: "박도현",
    type: "student",
    studentNumber: "290408",
    classNo: 4,
    cohort: 29,
    gender: "male",
    track: "domestic",
    department: null,
    // 재입학은 명부의 기수와 학번이 어긋날 수 있어서 심사자가 알아야 한다.
    isReenrolled: true,
    phoneNumber: "010-3355-9021",
    birthday: "2007-04-08",
    dormRoom: 405,
    description: "휴학 후 복학했습니다. 29기입니다.",
    avatarUrl: null,
    submittedAt: "2026-07-12T02:05:00.000Z",
  },
  {
    id: 304,
    name: "정하윤",
    type: "teacher",
    studentNumber: null,
    classNo: null,
    cohort: null,
    gender: "female",
    track: null,
    department: "과학기술부",
    isReenrolled: false,
    phoneNumber: "010-9981-2276",
    birthday: "1987-11-02",
    dormRoom: null,
    description: null,
    avatarUrl: null,
    submittedAt: "2026-07-12T08:33:00.000Z",
  },
  {
    id: 305,
    name: "윤채원",
    type: "student",
    studentNumber: "300231",
    classNo: 2,
    cohort: 30,
    gender: "female",
    track: "international",
    department: null,
    isReenrolled: false,
    phoneNumber: null,
    birthday: null,
    dormRoom: null,
    // 자기소개는 DB상 2000자까지 들어온다. 카드가 이걸로 늘어나면 안 된다.
    description:
      "안녕하세요! 30기 윤채원입니다. 국제반에 지원했고 앞으로 학교 생활을 열심히 해보려고 합니다. 동아리는 아직 정하지 못했는데 방송부나 과학기술부에 관심이 있어서 둘 다 알아보는 중이에요. 혹시 먼저 들어가 계신 선배님이 있다면 이야기 나눠보고 싶습니다. 기숙사 배정은 아직 안 나왔고 나오는 대로 다시 알려드리겠습니다. 승인 부탁드립니다. 감사합니다!",
    avatarUrl: null,
    submittedAt: "2026-07-13T01:20:00.000Z",
  },
  {
    id: 306,
    name: "임태경",
    type: "alumni",
    studentNumber: null,
    classNo: null,
    cohort: 24,
    gender: "male",
    track: null,
    department: null,
    isReenrolled: false,
    phoneNumber: "010-4408-7719",
    birthday: "2002-06-30",
    dormRoom: null,
    description: "24기 졸업생입니다.",
    avatarUrl: null,
    submittedAt: "2026-07-13T23:47:00.000Z",
  },
]

// 현재 앱 관리자. profiles where role='admin' and deleted_at is null.
export const mockAppAdmins: AppAdminProfile[] = [
  {
    id: 1,
    name: "김민족",
    type: "student",
    cohort: 30,
    department: "과학기술부",
    avatarUrl: null,
    isMe: true,
  },
  {
    id: 12,
    name: "정하윤",
    type: "teacher",
    cohort: null,
    department: "학습부",
    avatarUrl: null,
  },
]

// 관리자로 세울 수 있는 사람. profiles where status='accepted' and role='user'.
// set_app_admin이 accepted가 아니면 거절하므로(accepted profile required) pending은 여기 없다 --
// 가입 승인이 먼저다.
export const mockAdminCandidates: AppAdminProfile[] = [
  { id: 7, name: "이서준", type: "student", cohort: 29, department: null, avatarUrl: null },
  {
    id: 18,
    name: "박지우",
    type: "student",
    cohort: 30,
    department: "문화기획부",
    avatarUrl: null,
  },
  { id: 23, name: "최윤서", type: "teacher", cohort: null, department: "학습부", avatarUrl: null },
  { id: 41, name: "한도윤", type: "alumni", cohort: 26, department: null, avatarUrl: null },
]
