import { CURRENT_USER } from "~/lib/messenger/constants"
import type { Room } from "~/lib/messenger/types"

export const seedRooms: Room[] = [
  {
    id: 101,
    type: "direct",
    name: "Minji Kang",
    avatarUrl: null,
    participants: [CURRENT_USER, { id: 2, name: "Minji Kang", avatarUrl: null }],
    unreadCount: 2,
    messages: [
      {
        id: 1001,
        senderId: 2,
        content: "Are you still in the science building?",
        createdAt: "2026-07-03T20:41:00.000Z",
      },
      {
        id: 1002,
        senderId: 1,
        content: "Yes, finishing the lab notes now.",
        createdAt: "2026-07-03T20:42:00.000Z",
        read: true,
        readBy: [2],
      },
      {
        id: 1003,
        senderId: 2,
        replyTo: {
          messageId: 1002,
          author: "You",
          text: "Yes, finishing the lab notes now.",
        },
        content:
          "Perfect. Can you send the board photo again? The first image was cropped on my phone.",
        createdAt: "2026-07-03T20:43:00.000Z",
      },
      {
        // Nested reply on purpose: the viewer renders only one level, so tapping the preview walks the chain.
        id: 1004,
        senderId: 1,
        replyTo: {
          messageId: 1003,
          author: "Minji Kang",
          text: "Perfect. Can you send the board photo again? The first image was cropped on my phone.",
        },
        content: "Resending it now, uncropped.",
        createdAt: "2026-07-03T20:43:30.000Z",
        read: true,
        readBy: [2],
      },
      {
        id: 1005,
        senderId: 1,
        attachments: [
          {
            id: 2001,
            src: "/messenger/whiteboard-snapshot.png",
            name: "Whiteboard snapshot",
            contentType: "image/png",
          },
        ],
        createdAt: "2026-07-03T20:44:00.000Z",
        read: true,
        readBy: [2],
      },
      {
        id: 1006,
        senderId: 1,
        attachments: [
          {
            id: 2002,
            src: "/messenger/lab-bench-wide-shot.png",
            name: "Lab bench wide shot",
            contentType: "image/png",
            width: 1600,
            height: 900,
          },
        ],
        createdAt: "2026-07-03T20:44:05.000Z",
        read: true,
        readBy: [2],
      },
      {
        id: 1007,
        senderId: 1,
        attachments: [
          {
            id: 2003,
            src: "/messenger/poster-full-page.png",
            name: "Poster full page",
            contentType: "image/png",
            width: 720,
            height: 1600,
          },
        ],
        createdAt: "2026-07-03T20:44:10.000Z",
        read: true,
        readBy: [2],
      },
      {
        id: 1008,
        senderId: 1,
        attachments: [
          {
            id: 2004,
            src: "/messenger/hallway-panorama.png",
            name: "Hallway panorama",
            contentType: "image/png",
            width: 1800,
            height: 500,
          },
        ],
        createdAt: "2026-07-03T20:44:15.000Z",
        read: true,
        readBy: [2],
      },
      {
        id: 1009,
        senderId: 2,
        attachments: [
          {
            id: 2005,
            src: "/messenger/board-photo-1.png",
            name: "Board photo 1",
            contentType: "image/png",
            width: 1200,
            height: 1600,
          },
          {
            id: 2006,
            src: "/messenger/board-photo-2.png",
            name: "Board photo 2",
            contentType: "image/png",
            width: 1600,
            height: 1200,
          },
        ],
        createdAt: "2026-07-03T20:44:18.000Z",
      },
      {
        id: 1010,
        senderId: 1,
        attachments: [
          {
            id: 2007,
            src: "/messenger/reaction-step-1.png",
            name: "Reaction step 1",
            contentType: "image/png",
            width: 1200,
            height: 1600,
          },
          {
            id: 2008,
            src: "/messenger/reaction-step-2.png",
            name: "Reaction step 2",
            contentType: "image/png",
            width: 1200,
            height: 900,
          },
          {
            id: 2009,
            src: "/messenger/reaction-step-3.png",
            name: "Reaction step 3",
            contentType: "image/png",
            width: 1200,
            height: 900,
          },
        ],
        createdAt: "2026-07-03T20:44:19.000Z",
        read: true,
        readBy: [2],
      },
      {
        id: 1011,
        senderId: 2,
        attachments: [
          {
            id: 2010,
            src: "/messenger/angle-1.png",
            name: "Angle 1",
            contentType: "image/png",
          },
          {
            id: 2011,
            src: "/messenger/angle-2.png",
            name: "Angle 2",
            contentType: "image/png",
          },
          {
            id: 2012,
            src: "/messenger/angle-3.png",
            name: "Angle 3",
            contentType: "image/png",
          },
          {
            id: 2013,
            src: "/messenger/angle-4.png",
            name: "Angle 4",
            contentType: "image/png",
          },
        ],
        createdAt: "2026-07-03T20:44:19.500Z",
      },
      {
        id: 1012,
        senderId: 1,
        attachments: [
          {
            id: 2014,
            src: "/messenger/notes-page-1.png",
            name: "Notes page 1",
            contentType: "image/png",
          },
          {
            id: 2015,
            src: "/messenger/notes-page-2.png",
            name: "Notes page 2",
            contentType: "image/png",
          },
          {
            id: 2016,
            src: "/messenger/notes-page-3.png",
            name: "Notes page 3",
            contentType: "image/png",
          },
          {
            id: 2017,
            src: "/messenger/notes-page-4.png",
            name: "Notes page 4",
            contentType: "image/png",
          },
          {
            id: 2018,
            src: "/messenger/notes-page-5.png",
            name: "Notes page 5",
            contentType: "image/png",
          },
          {
            id: 2019,
            src: "/messenger/notes-page-6.png",
            name: "Notes page 6",
            contentType: "image/png",
          },
        ],
        createdAt: "2026-07-03T20:44:19.800Z",
        read: true,
        readBy: [2],
      },
      {
        id: 1013,
        senderId: 2,
        attachments: [
          {
            id: 2020,
            src: "/messenger/poster-reveal.mp4",
            name: "Poster reveal.mp4",
            contentType: "video/mp4",
            sizeBytes: 39_102,
            width: 360,
            height: 640,
            durationSeconds: 4,
          },
        ],
        createdAt: "2026-07-03T20:44:19.900Z",
      },
      {
        id: 1014,
        senderId: 1,
        content:
          "This one should include the whole reaction sequence. I also marked the step where Professor Kim said most people make the sign mistake, so check that part before copying it into the shared notes.",
        createdAt: "2026-07-03T20:44:20.000Z",
        reactions: [{ userId: 2, value: "👍" }],
        read: true,
        readBy: [2],
      },
      {
        id: 1015,
        senderId: 2,
        content:
          "Got it. The long paragraph wraps correctly here too, which is useful for checking the message bubble width on desktop and mobile layouts.",
        createdAt: "2026-07-03T20:46:00.000Z",
      },
    ],
  },
  {
    id: 102,
    type: "group",
    name: "Student Council Ops",
    avatarUrl: null,
    participants: [
      CURRENT_USER,
      { id: 3, name: "Daniel Choi", avatarUrl: null },
      { id: 4, name: "Sora Han", avatarUrl: null },
      { id: 5, name: "Yujin Seo", avatarUrl: null },
    ],
    messages: [
      {
        id: 1016,
        senderId: 3,
        content: "I moved the checklist into the drive folder.",
        createdAt: "2026-07-03T19:11:00.000Z",
        pinnedAt: "2026-07-03T19:20:00.000Z",
        pinnedBy: 3,
      },
      {
        id: 1017,
        senderId: 3,
        attachments: [
          {
            id: 2021,
            name: "Volunteer checklist.pdf",
            contentType: "application/pdf",
            sizeBytes: 348_160,
          },
        ],
        createdAt: "2026-07-03T19:11:05.000Z",
      },
      {
        id: 1018,
        senderId: 3,
        attachments: [
          {
            id: 2022,
            name: "Budget breakdown.xlsx",
            contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            sizeBytes: 92_400,
          },
        ],
        createdAt: "2026-07-03T19:12:00.000Z",
      },
      {
        id: 1019,
        senderId: 3,
        attachments: [
          {
            id: 2023,
            name: "Sponsor agreement.docx",
            contentType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            sizeBytes: 154_000,
          },
        ],
        createdAt: "2026-07-03T19:12:01.000Z",
      },
      {
        id: 1020,
        senderId: 3,
        attachments: [
          {
            id: 2024,
            name: "Booth layout.pdf",
            contentType: "application/pdf",
            sizeBytes: 1_248_000,
          },
        ],
        createdAt: "2026-07-03T19:12:02.000Z",
      },
      {
        id: 1021,
        senderId: 3,
        attachments: [
          {
            id: 2025,
            name: "Vendor contacts.csv",
            contentType: "text/csv",
            sizeBytes: 3_540_000,
          },
        ],
        createdAt: "2026-07-03T19:12:03.000Z",
      },
      {
        id: 1022,
        senderId: 4,
        attachments: [
          {
            id: 2026,
            src: "/messenger/rehearsal-clip.wav",
            name: "Rehearsal clip.wav",
            contentType: "audio/wav",
            sizeBytes: 96_044,
            durationSeconds: 6,
          },
        ],
        createdAt: "2026-07-03T19:12:04.000Z",
      },
      {
        id: 1023,
        senderId: 5,
        attachments: [
          {
            id: 2027,
            src: "/messenger/booth-walkthrough.mp4",
            name: "Booth walkthrough.mp4",
            contentType: "video/mp4",
            sizeBytes: 60_905,
            width: 640,
            height: 360,
            durationSeconds: 6,
          },
        ],
        createdAt: "2026-07-03T19:12:05.000Z",
      },
      {
        // Dimensions withheld on purpose: exercises the reserved default ratio.
        id: 1024,
        senderId: 3,
        attachments: [
          {
            id: 2028,
            src: "/messenger/stage-check.mp4",
            name: "Stage check.mp4",
            contentType: "video/mp4",
            sizeBytes: 45_568,
          },
        ],
        createdAt: "2026-07-03T19:12:06.000Z",
      },
      {
        id: 1025,
        senderId: 4,
        content: "Great. I will verify the volunteer names before dinner.",
        createdAt: "2026-07-03T19:18:00.000Z",
        reactions: [
          { userId: 3, value: "❤️" },
          { userId: 5, value: "❤️" },
        ],
        readBy: [5],
      },
      {
        id: 1026,
        senderId: 1,
        content:
          "Please leave the booth layout unchanged until the advisor confirms the power outlets.",
        createdAt: "2026-07-03T19:24:00.000Z",
        reactions: [
          { userId: 3, value: "👍" },
          { userId: 4, value: "❤️" },
          { userId: 5, value: "😂" },
        ],
        read: true,
        readBy: [3, 4],
        pinnedAt: "2026-07-03T19:25:00.000Z",
        pinnedBy: 1,
      },
    ],
  },
  {
    id: 103,
    type: "direct",
    name: "Junseo Park",
    avatarUrl: null,
    muted: true,
    participants: [CURRENT_USER, { id: 6, name: "Junseo Park", avatarUrl: null }],
    messages: [
      {
        id: 1027,
        senderId: 6,
        content: "Long answer, but the short version is yes.",
        createdAt: "2026-07-03T18:32:00.000Z",
      },
    ],
  },
  {
    id: 104,
    type: "group",
    name: "Debate Prep Room",
    avatarUrl: null,
    unreadCount: 5,
    participants: [
      CURRENT_USER,
      { id: 7, name: "Arin Moon", avatarUrl: null },
      { id: 8, name: "Tae Kim", avatarUrl: null },
    ],
    messages: [
      {
        id: 1028,
        senderId: 7,
        attachments: [
          {
            id: 2029,
            src: "/messenger/debate-bracket.png",
            name: "Case map draft",
            contentType: "image/png",
          },
        ],
        createdAt: "2026-07-03T17:12:00.000Z",
      },
      {
        id: 1029,
        senderId: 8,
        content: "Photo attached. The second column needs the strongest evidence first.",
        createdAt: "2026-07-03T17:13:00.000Z",
      },
    ],
  },
  {
    id: 105,
    type: "direct",
    name: "Library Desk",
    avatarUrl: null,
    participants: [CURRENT_USER, { id: 9, name: "Library Desk", avatarUrl: null }],
    messages: [
      {
        id: 1030,
        senderId: 9,
        content: "Your reservation has been extended until 9:30 PM.",
        createdAt: "2026-07-03T15:07:00.000Z",
      },
    ],
  },
  {
    id: 106,
    type: "direct",
    name: "Hani Lee",
    avatarUrl: null,
    participants: [CURRENT_USER, { id: 10, name: "Hani Lee", avatarUrl: null }],
    messages: [
      {
        id: 1031,
        senderId: 1,
        content: "I left the notebook with the front desk.",
        createdAt: "2026-07-02T21:15:00.000Z",
        read: true,
        readBy: [10],
      },
      {
        id: 1032,
        senderId: 10,
        content: "Thanks! I will check after study hall.",
        createdAt: "2026-07-02T21:17:00.000Z",
      },
    ],
  },
  {
    id: 107,
    type: "direct",
    name: "Soyeon Kim",
    avatarUrl: null,
    participants: [CURRENT_USER, { id: 11, name: "Soyeon Kim", avatarUrl: null }],
    messages: [],
  },
  {
    id: 108,
    type: "direct",
    name: "Jaehyun Lim",
    avatarUrl: null,
    participants: [CURRENT_USER, { id: 12, name: "Jaehyun Lim", avatarUrl: null }],
    messages: [],
  },
  {
    id: 109,
    type: "direct",
    name: "Yebin Cho",
    avatarUrl: null,
    participants: [CURRENT_USER, { id: 13, name: "Yebin Cho", avatarUrl: null }],
    messages: [],
  },
  {
    id: 110,
    type: "group",
    name: "Dorm A Floor 2",
    avatarUrl: null,
    participants: [
      CURRENT_USER,
      { id: 14, name: "Hyun Woo", avatarUrl: null },
      { id: 15, name: "Seoha Yoon", avatarUrl: null },
    ],
    messages: [],
  },
  {
    id: 111,
    type: "group",
    name: "Math Team",
    avatarUrl: null,
    participants: [
      CURRENT_USER,
      { id: 16, name: "Jiho Nam", avatarUrl: null },
      { id: 17, name: "Eun Cha", avatarUrl: null },
      { id: 18, name: "Min Koo", avatarUrl: null },
    ],
    messages: [],
  },
  {
    id: 112,
    type: "group",
    name: "Orchestra Strings",
    avatarUrl: null,
    participants: [
      CURRENT_USER,
      { id: 19, name: "Haru Shin", avatarUrl: null },
      { id: 20, name: "Nari Bae", avatarUrl: null },
    ],
    messages: [],
  },
  {
    id: 113,
    type: "group",
    name: "Physics Lab 3",
    avatarUrl: null,
    participants: [
      CURRENT_USER,
      { id: 21, name: "Dohyun Kwon", avatarUrl: null },
      { id: 22, name: "Ray Jung", avatarUrl: null },
    ],
    messages: [],
  },
  {
    id: 114,
    type: "group",
    name: "Art Club Posters",
    avatarUrl: null,
    participants: [
      CURRENT_USER,
      { id: 23, name: "Mira Song", avatarUrl: null },
      { id: 24, name: "Taerin Oh", avatarUrl: null },
    ],
    messages: [],
  },
  {
    id: 115,
    type: "direct",
    name: "Cafeteria Office",
    avatarUrl: null,
    participants: [CURRENT_USER, { id: 25, name: "Cafeteria Office", avatarUrl: null }],
    messages: [],
  },
  {
    id: 116,
    type: "direct",
    name: "Semina Yoo",
    avatarUrl: null,
    participants: [CURRENT_USER, { id: 26, name: "Semina Yoo", avatarUrl: null }],
    messages: [],
  },
  {
    id: 117,
    type: "group",
    name: "Broadcast Team",
    avatarUrl: null,
    participants: [
      CURRENT_USER,
      { id: 27, name: "Noah Jin", avatarUrl: null },
      { id: 28, name: "Hani Seo", avatarUrl: null },
    ],
    messages: [],
  },
  {
    id: 118,
    type: "direct",
    name: "Admissions Desk",
    avatarUrl: null,
    participants: [CURRENT_USER, { id: 29, name: "Admissions Desk", avatarUrl: null }],
    messages: [],
  },
]
