import type { AppNotification } from "~/lib/noti/types"

// list_notifications()가 붙을 때까지의 대역. 종류를 한 번씩 다 덮어 화면이 모든 분기를 그린다.
// 값은 스키마가 실제로 담는 것만 쓴다 -- 서버가 안 주는 필드는 여기에도 없다.
//
// 채팅 알림은 없다. 알림함과 채팅은 별개 체계이고, 그건 빠뜨린 게 아니라 결정이다 --
// 근거는 supabase/schemas/06-notifications.sql 상단.

// 고정 기준 시각. Date.now()로 잡으면 SSR과 브라우저가 다른 시계를 읽어 hydration이 어긋난다.
const BASE = Date.parse("2026-07-24T09:00:00Z")
const minutesAgo = (minutes: number) => new Date(BASE - minutes * 60_000).toISOString()

export const mockNotifications: AppNotification[] = [
  {
    id: 13,
    type: "reaction_summary",
    // 집계 알림에는 단일 actor가 없다. 익명 개인 행 대신 집계 창의 인원수만 payload에 둔다.
    actor: null,
    actorIsAnonymous: false,
    space: { pubId: "student-council", name: "행정위원회", type: "group" },
    post: { pubId: "c0ffee00-0000-4000-8000-000000000001", title: "기말고사 일정 안내" },
    comment: null,
    payload: { reaction_count: 3 },
    readAt: null,
    createdAt: minutesAgo(1),
  },
  {
    id: 12,
    type: "post_comment",
    // 운영진 댓글: 개인 actor는 지우고 게시 당시 운영진 귀속만 내려준다.
    actor: null,
    actorAttribution: "staff",
    actorIsAnonymous: true,
    space: { pubId: "student-council", name: "행정위원회", type: "group" },
    post: { pubId: "c0ffee00-0000-4000-8000-000000000001", title: "기말고사 일정 안내" },
    comment: { id: 401, content: "혹시 시험 범위도 같이 올라오나요?", isDeleted: false },
    payload: null,
    readAt: null,
    createdAt: minutesAgo(3),
  },
  {
    id: 11,
    type: "comment_mention",
    actor: { id: 7, name: "김서연", avatarUrl: null },
    actorIsAnonymous: false,
    space: { pubId: "market", name: "민사고 먹9 사9 팔9", type: "community" },
    post: { pubId: "c0ffee00-0000-4000-8000-000000000002", title: "교재 나눔합니다" },
    comment: { id: 402, content: "이거 아직 남아 있나요? 저 필요해요!", isDeleted: false },
    payload: null,
    readAt: null,
    createdAt: minutesAgo(28),
  },
  {
    id: 10,
    type: "space_join_request",
    actor: { id: 12, name: "박도윤", avatarUrl: null },
    actorIsAnonymous: false,
    space: { pubId: "student-council", name: "행정위원회", type: "group" },
    post: null,
    comment: null,
    payload: null,
    readAt: null,
    createdAt: minutesAgo(95),
  },
  {
    id: 9,
    type: "comment_reply",
    actor: { id: 3, name: "이하준", avatarUrl: null },
    actorIsAnonymous: false,
    space: { pubId: "class-30", name: "30기 민사 재학생", type: "community" },
    post: { pubId: "c0ffee00-0000-4000-8000-000000000003", title: "기말고사 공부법 공유해요!" },
    comment: {
      id: 403,
      content: "저도 그 방법 써봤는데 확실히 효율이 좋더라고요.",
      isDeleted: false,
    },
    payload: null,
    readAt: minutesAgo(180),
    createdAt: minutesAgo(240),
  },
  {
    id: 8,
    type: "space_anonymity_suspended",
    // 모더레이션 알림은 actor가 없다. suspended_by의 select를 이미 회수해 뒀는데
    // ("누가 걸었는지까지 알면 보복 대상이 된다") 알림에 실으면 그 결정이 무효가 된다.
    actor: null,
    actorIsAnonymous: false,
    space: { pubId: "market", name: "민사고 먹9 사9 팔9", type: "community" },
    post: null,
    comment: null,
    payload: { suspended_until: new Date(BASE + 2 * 24 * 60 * 60_000).toISOString() },
    readAt: null,
    createdAt: minutesAgo(300),
  },
  {
    id: 7,
    type: "post_mention",
    actor: { id: 5, name: "최민준", avatarUrl: null },
    actorIsAnonymous: false,
    space: { pubId: "clubs", name: "동아리", type: "group" },
    post: { pubId: "c0ffee00-0000-4000-8000-000000000004", title: "밴드부 신입 모집" },
    comment: null,
    payload: null,
    readAt: minutesAgo(400),
    createdAt: minutesAgo(420),
  },
  {
    id: 6,
    type: "space_join_approved",
    actor: null,
    actorIsAnonymous: false,
    space: { pubId: "class-30", name: "30기 민사 재학생", type: "community" },
    post: null,
    comment: null,
    payload: null,
    readAt: minutesAgo(1400),
    createdAt: minutesAgo(1500),
  },
  {
    id: 5,
    type: "space_invited",
    actor: { id: 9, name: "정예린", avatarUrl: null },
    actorIsAnonymous: false,
    space: { pubId: "lost-and-found", name: "민사고 떨99 줍9", type: "community" },
    post: null,
    comment: null,
    payload: null,
    readAt: minutesAgo(1600),
    createdAt: minutesAgo(1700),
  },
  {
    id: 4,
    type: "post_removed",
    actor: null,
    actorIsAnonymous: false,
    space: { pubId: "market", name: "민사고 먹9 사9 팔9", type: "community" },
    // 글은 소프트 삭제됐다. 제목은 내가 쓴 것이라 보여줘도 되지만 링크는 걸 수 없다.
    post: { pubId: "c0ffee00-0000-4000-8000-000000000005", title: "노트북 팝니다" },
    comment: null,
    payload: null,
    readAt: minutesAgo(2800),
    createdAt: minutesAgo(2880),
  },
  {
    id: 3,
    type: "space_role_changed",
    actor: null,
    actorIsAnonymous: false,
    space: { pubId: "clubs", name: "동아리", type: "group" },
    post: null,
    comment: null,
    payload: { from: "member", to: "admin" },
    readAt: minutesAgo(4200),
    createdAt: minutesAgo(4320),
  },
  {
    id: 2,
    type: "comment_removed",
    actor: null,
    actorIsAnonymous: false,
    space: { pubId: "class-30", name: "30기 민사 재학생", type: "community" },
    post: { pubId: "c0ffee00-0000-4000-8000-000000000006", title: "야자 시간 조정 건의" },
    // 삭제된 댓글은 content가 비어서 온다(soft_delete_comment가 지운다).
    comment: { id: 404, content: null, isDeleted: true },
    payload: null,
    readAt: minutesAgo(5700),
    createdAt: minutesAgo(5760),
  },
  {
    id: 1,
    type: "space_join_rejected",
    actor: null,
    actorIsAnonymous: false,
    space: { pubId: "dormitory", name: "기숙사", type: "group" },
    post: null,
    comment: null,
    payload: null,
    readAt: minutesAgo(10000),
    createdAt: minutesAgo(10080),
  },
]
