import { CURRENT_USER } from "../app/lib/messenger/constants"
import type { Room } from "../app/lib/messenger/types"

export const seedRooms: Room[] = [
  {
    id: "room-minji",
    type: "direct",
    name: "Minji Kang",
    initials: "MK",
    participants: [CURRENT_USER, { id: "minji", name: "Minji Kang", initials: "MK" }],
    unreadCount: 2,
    messages: [
      {
        id: "minji-1",
        senderId: "minji",
        content: "Are you still in the science building?",
        createdAt: "2026-07-03T20:41:00.000Z",
      },
      {
        id: "minji-2",
        senderId: "me",
        content: "Yes, finishing the lab notes now.",
        createdAt: "2026-07-03T20:42:00.000Z",
        read: true,
        readBy: ["minji"],
      },
      {
        id: "minji-3",
        senderId: "minji",
        replyTo: {
          messageId: "minji-2",
          author: "You",
          text: "Yes, finishing the lab notes now.",
        },
        content:
          "Perfect. Can you send the board photo again? The first image was cropped on my phone.",
        createdAt: "2026-07-03T20:43:00.000Z",
      },
      {
        id: "minji-4",
        senderId: "me",
        attachments: [
          {
            id: "minji-4-file-1",
            name: "Whiteboard snapshot",
            contentType: "image/jpeg",
          },
        ],
        createdAt: "2026-07-03T20:44:00.000Z",
        read: true,
        readBy: ["minji"],
      },
      {
        id: "minji-4-landscape",
        senderId: "me",
        attachments: [
          {
            id: "minji-4-landscape-1",
            name: "Lab bench wide shot",
            contentType: "image/jpeg",
            width: 1600,
            height: 900,
          },
        ],
        createdAt: "2026-07-03T20:44:05.000Z",
        read: true,
        readBy: ["minji"],
      },
      {
        id: "minji-4-portrait",
        senderId: "me",
        attachments: [
          {
            id: "minji-4-portrait-1",
            name: "Poster full page",
            contentType: "image/jpeg",
            width: 720,
            height: 1600,
          },
        ],
        createdAt: "2026-07-03T20:44:10.000Z",
        read: true,
        readBy: ["minji"],
      },
      {
        id: "minji-4-panorama",
        senderId: "me",
        attachments: [
          {
            id: "minji-4-panorama-1",
            name: "Hallway panorama",
            contentType: "image/jpeg",
            width: 1800,
            height: 500,
          },
        ],
        createdAt: "2026-07-03T20:44:15.000Z",
        read: true,
        readBy: ["minji"],
      },
      {
        id: "minji-4-pair",
        senderId: "minji",
        attachments: [
          {
            id: "minji-4-pair-1",
            name: "Board photo 1",
            contentType: "image/jpeg",
            width: 1200,
            height: 1600,
          },
          {
            id: "minji-4-pair-2",
            name: "Board photo 2",
            contentType: "image/jpeg",
            width: 1600,
            height: 1200,
          },
        ],
        createdAt: "2026-07-03T20:44:18.000Z",
      },
      {
        id: "minji-4-trio",
        senderId: "me",
        attachments: [
          {
            id: "minji-4-trio-1",
            name: "Reaction step 1",
            contentType: "image/jpeg",
            width: 1200,
            height: 1600,
          },
          {
            id: "minji-4-trio-2",
            name: "Reaction step 2",
            contentType: "image/jpeg",
            width: 1200,
            height: 900,
          },
          {
            id: "minji-4-trio-3",
            name: "Reaction step 3",
            contentType: "image/jpeg",
            width: 1200,
            height: 900,
          },
        ],
        createdAt: "2026-07-03T20:44:19.000Z",
        read: true,
        readBy: ["minji"],
      },
      {
        id: "minji-4-quad",
        senderId: "minji",
        attachments: [
          { id: "minji-4-quad-1", name: "Angle 1", contentType: "image/jpeg" },
          { id: "minji-4-quad-2", name: "Angle 2", contentType: "image/jpeg" },
          { id: "minji-4-quad-3", name: "Angle 3", contentType: "image/jpeg" },
          { id: "minji-4-quad-4", name: "Angle 4", contentType: "image/jpeg" },
        ],
        createdAt: "2026-07-03T20:44:19.500Z",
      },
      {
        id: "minji-4-overflow",
        senderId: "me",
        attachments: [
          { id: "minji-4-overflow-1", name: "Notes page 1", contentType: "image/png" },
          { id: "minji-4-overflow-2", name: "Notes page 2", contentType: "image/png" },
          { id: "minji-4-overflow-3", name: "Notes page 3", contentType: "image/png" },
          { id: "minji-4-overflow-4", name: "Notes page 4", contentType: "image/png" },
          { id: "minji-4-overflow-5", name: "Notes page 5", contentType: "image/png" },
          { id: "minji-4-overflow-6", name: "Notes page 6", contentType: "image/png" },
        ],
        createdAt: "2026-07-03T20:44:19.800Z",
        read: true,
        readBy: ["minji"],
      },
      {
        id: "minji-5",
        senderId: "me",
        content:
          "This one should include the whole reaction sequence. I also marked the step where Professor Kim said most people make the sign mistake, so check that part before copying it into the shared notes.",
        createdAt: "2026-07-03T20:44:20.000Z",
        reactions: [{ userId: "minji", value: "👍" }],
        read: true,
        readBy: ["minji"],
      },
      {
        id: "minji-6",
        senderId: "minji",
        content:
          "Got it. The long paragraph wraps correctly here too, which is useful for checking the message bubble width on desktop and mobile layouts.",
        createdAt: "2026-07-03T20:46:00.000Z",
      },
    ],
  },
  {
    id: "room-council",
    type: "group",
    name: "Student Council Ops",
    initials: "SC",
    participants: [
      CURRENT_USER,
      { id: "daniel", name: "Daniel Choi", initials: "DC" },
      { id: "sora", name: "Sora Han", initials: "SH" },
      { id: "yujin", name: "Yujin Seo", initials: "YS" },
    ],
    messages: [
      {
        id: "council-1",
        senderId: "daniel",
        content: "I moved the checklist into the drive folder.",
        createdAt: "2026-07-03T19:11:00.000Z",
      },
      {
        id: "council-1-file",
        senderId: "daniel",
        attachments: [
          {
            id: "council-1-file-1",
            name: "Volunteer checklist.pdf",
            contentType: "application/pdf",
            sizeBytes: 348_160,
          },
        ],
        createdAt: "2026-07-03T19:11:05.000Z",
      },
      {
        id: "council-1-budget-file",
        senderId: "daniel",
        attachments: [
          {
            id: "council-1-budget-file-1",
            name: "Budget breakdown.xlsx",
            contentType:
              "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            sizeBytes: 92_400,
          },
        ],
        createdAt: "2026-07-03T19:12:00.000Z",
      },
      {
        id: "council-1-sponsor-file",
        senderId: "daniel",
        attachments: [
          {
            id: "council-1-sponsor-file-1",
            name: "Sponsor agreement.docx",
            contentType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            sizeBytes: 154_000,
          },
        ],
        createdAt: "2026-07-03T19:12:01.000Z",
      },
      {
        id: "council-1-layout-file",
        senderId: "daniel",
        attachments: [
          {
            id: "council-1-layout-file-1",
            name: "Booth layout.pdf",
            contentType: "application/pdf",
            sizeBytes: 1_248_000,
          },
        ],
        createdAt: "2026-07-03T19:12:02.000Z",
      },
      {
        id: "council-1-vendor-file",
        senderId: "daniel",
        attachments: [
          {
            id: "council-1-vendor-file-1",
            name: "Vendor contacts.zip",
            contentType: "application/zip",
            sizeBytes: 3_540_000,
          },
        ],
        createdAt: "2026-07-03T19:12:03.000Z",
      },
      {
        id: "council-2",
        senderId: "sora",
        content: "Great. I will verify the volunteer names before dinner.",
        createdAt: "2026-07-03T19:18:00.000Z",
        reactions: [
          { userId: "daniel", value: "❤️" },
          { userId: "yujin", value: "❤️" },
        ],
        readBy: ["yujin"],
      },
      {
        id: "council-3",
        senderId: "me",
        content:
          "Please leave the booth layout unchanged until the advisor confirms the power outlets.",
        createdAt: "2026-07-03T19:24:00.000Z",
        reactions: [
          { userId: "daniel", value: "👍" },
          { userId: "sora", value: "❤️" },
          { userId: "yujin", value: "😂" },
        ],
        read: true,
        readBy: ["daniel", "sora"],
      },
    ],
  },
  {
    id: "room-junseo",
    type: "direct",
    name: "Junseo Park",
    initials: "JP",
    muted: true,
    participants: [CURRENT_USER, { id: "junseo", name: "Junseo Park", initials: "JP" }],
    messages: [
      {
        id: "junseo-1",
        senderId: "junseo",
        content: "Long answer, but the short version is yes.",
        createdAt: "2026-07-03T18:32:00.000Z",
      },
    ],
  },
  {
    id: "room-debate",
    type: "group",
    name: "Debate Prep Room",
    initials: "DP",
    unreadCount: 5,
    participants: [
      CURRENT_USER,
      { id: "arin", name: "Arin Moon", initials: "AM" },
      { id: "tae", name: "Tae Kim", initials: "TK" },
    ],
    messages: [
      {
        id: "debate-1",
        senderId: "arin",
        attachments: [
          {
            id: "debate-1-file-1",
            name: "Case map draft",
            contentType: "image/png",
          },
        ],
        createdAt: "2026-07-03T17:12:00.000Z",
      },
      {
        id: "debate-2",
        senderId: "tae",
        content: "Photo attached. The second column needs the strongest evidence first.",
        createdAt: "2026-07-03T17:13:00.000Z",
      },
    ],
  },
  {
    id: "room-library",
    type: "direct",
    name: "Library Desk",
    initials: "LD",
    participants: [CURRENT_USER, { id: "library", name: "Library Desk", initials: "LD" }],
    messages: [
      {
        id: "library-1",
        senderId: "library",
        content: "Your reservation has been extended until 9:30 PM.",
        createdAt: "2026-07-03T15:07:00.000Z",
      },
    ],
  },
  {
    id: "room-hani",
    type: "direct",
    name: "Hani Lee",
    initials: "HL",
    participants: [CURRENT_USER, { id: "hani", name: "Hani Lee", initials: "HL" }],
    messages: [
      {
        id: "hani-1",
        senderId: "me",
        content: "I left the notebook with the front desk.",
        createdAt: "2026-07-02T21:15:00.000Z",
        read: true,
        readBy: ["hani"],
      },
      {
        id: "hani-2",
        senderId: "hani",
        content: "Thanks! I will check after study hall.",
        createdAt: "2026-07-02T21:17:00.000Z",
      },
    ],
  },
  {
    id: "room-soyeon",
    type: "direct",
    name: "Soyeon Kim",
    initials: "SK",
    participants: [CURRENT_USER, { id: "soyeon", name: "Soyeon Kim", initials: "SK" }],
    messages: [],
  },
  {
    id: "room-jaehyun",
    type: "direct",
    name: "Jaehyun Lim",
    initials: "JL",
    participants: [CURRENT_USER, { id: "jaehyun", name: "Jaehyun Lim", initials: "JL" }],
    messages: [],
  },
  {
    id: "room-yebin",
    type: "direct",
    name: "Yebin Cho",
    initials: "YC",
    participants: [CURRENT_USER, { id: "yebin", name: "Yebin Cho", initials: "YC" }],
    messages: [],
  },
  {
    id: "room-dorm-a",
    type: "group",
    name: "Dorm A Floor 2",
    initials: "DA",
    participants: [
      CURRENT_USER,
      { id: "hyun", name: "Hyun Woo", initials: "HW" },
      { id: "seoha", name: "Seoha Yoon", initials: "SY" },
    ],
    messages: [],
  },
  {
    id: "room-math-team",
    type: "group",
    name: "Math Team",
    initials: "MT",
    participants: [
      CURRENT_USER,
      { id: "jiho", name: "Jiho Nam", initials: "JN" },
      { id: "eun", name: "Eun Cha", initials: "EC" },
      { id: "min", name: "Min Koo", initials: "MK" },
    ],
    messages: [],
  },
  {
    id: "room-orchestra",
    type: "group",
    name: "Orchestra Strings",
    initials: "OS",
    participants: [
      CURRENT_USER,
      { id: "haru", name: "Haru Shin", initials: "HS" },
      { id: "nari", name: "Nari Bae", initials: "NB" },
    ],
    messages: [],
  },
  {
    id: "room-physics",
    type: "group",
    name: "Physics Lab 3",
    initials: "PL",
    participants: [
      CURRENT_USER,
      { id: "dohyun", name: "Dohyun Kwon", initials: "DK" },
      { id: "ray", name: "Ray Jung", initials: "RJ" },
    ],
    messages: [],
  },
  {
    id: "room-art-club",
    type: "group",
    name: "Art Club Posters",
    initials: "AC",
    participants: [
      CURRENT_USER,
      { id: "mira", name: "Mira Song", initials: "MS" },
      { id: "taerin", name: "Taerin Oh", initials: "TO" },
    ],
    messages: [],
  },
  {
    id: "room-cafeteria",
    type: "direct",
    name: "Cafeteria Office",
    initials: "CO",
    participants: [CURRENT_USER, { id: "cafeteria", name: "Cafeteria Office", initials: "CO" }],
    messages: [],
  },
  {
    id: "room-semina",
    type: "direct",
    name: "Semina Yoo",
    initials: "SY",
    participants: [CURRENT_USER, { id: "semina", name: "Semina Yoo", initials: "SY" }],
    messages: [],
  },
  {
    id: "room-broadcast",
    type: "group",
    name: "Broadcast Team",
    initials: "BT",
    participants: [
      CURRENT_USER,
      { id: "noah", name: "Noah Jin", initials: "NJ" },
      { id: "hani2", name: "Hani Seo", initials: "HS" },
    ],
    messages: [],
  },
  {
    id: "room-admissions",
    type: "direct",
    name: "Admissions Desk",
    initials: "AD",
    participants: [CURRENT_USER, { id: "admissions", name: "Admissions Desk", initials: "AD" }],
    messages: [],
  },
]
